### ISSUE TITLE
doesn't work for the company 

### ISSUE THREAD

**Issue by Leftman12** [EyeOfDarkness/Advance-Lighting#3]
I really liked the mod, you can customize the glow to suit you, it looks awesome, but there is one problem. In the settings there is a function to turn off the glow of units, cores, power nodes, etc. But when I go into the company, the light remains. I searched through all the settings and available videos to solve the problem, but found nothing. Moreover, on Erekira everything is fine and everything works. I hope they fix this, or tell me how to fix it.

**Comment by EyeOfDarkness** [comment]
what?
